
var list = [
  {
    "Week 1": "",
    "Player Name": "Russell Wilson",
    "Rush Yards": 45,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 325,
    "Pass TD": 1,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "W",
    "Week Total": 21.5
  },
  {
    "Week 1": "",
    "Player Name": "Lamar Jackson",
    "Rush Yards": "NA",
    "Rush TD": "NA",
    "Rec Yards": "NA",
    "Rec TD": "NA",
    "Pass Yards": "NA",
    "Pass TD": "NA",
    "Interceptions": "NA",
    "Fumbles": "NA",
    "2PC": 0,
    "Win/Lose": "NA",
    "Week Total": "NA"
  },
  {
    "Week 1": "",
    "Player Name": "Drew Brees",
    "Rush Yards": 5,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 208,
    "Pass TD": 1,
    "Interceptions": 1,
    "Fumbles": 1,
    "2PC": 0,
    "Win/Lose": "L",
    "Week Total": 8.82
  },
  {
    "Week 1": "",
    "Player Name": "Patrick Mahomes",
    "Rush Yards": "NA",
    "Rush TD": "NA",
    "Rec Yards": "NA",
    "Rec TD": "NA",
    "Pass Yards": "NA",
    "Pass TD": "NA",
    "Interceptions": "NA",
    "Fumbles": "NA",
    "2PC": 0,
    "Win/Lose": "NA",
    "Week Total": "NA"
  },
  {
    "Week 1": "",
    "Player Name": "",
    "Rush Yards": "",
    "Rush TD": "",
    "Rec Yards": "",
    "Rec TD": "",
    "Pass Yards": "",
    "Pass TD": "",
    "Interceptions": "",
    "Fumbles": "",
    "2PC": "",
    "Win/Lose": "",
    "Week Total": ""
  },
  {
    "Week 1": "Week 2",
    "Player Name": "Player Name",
    "Rush Yards": "Rush Yards",
    "Rush TD": "Rush TD",
    "Rec Yards": "Rec Yards",
    "Rec TD": "Rec TD",
    "Pass Yards": "Pass Yards",
    "Pass TD": "Pass TD",
    "Interceptions": "Interceptions",
    "Fumbles": "Fumbles",
    "2PC": "2PC",
    "Win/Lose": "Win/Lose",
    "Week Total": "Week Total"
  },
  {
    "Week 1": "",
    "Player Name": "Russell Wilson",
    "Rush Yards": 64,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 277,
    "Pass TD": 1,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "L",
    "Week Total": 21.48
  },
  {
    "Week 1": "",
    "Player Name": "Lamar Jackson",
    "Rush Yards": 143,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 365,
    "Pass TD": 1,
    "Interceptions": 2,
    "Fumbles": 1,
    "2PC": 0,
    "Win/Lose": "L",
    "Week Total": 26.9
  },
  {
    "Week 1": "",
    "Player Name": "Drew Brees",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "NA",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "Patrick Mahomes",
    "Rush Yards": 53,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 321,
    "Pass TD": 5,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "W",
    "Week Total": 38.14
  },
  {
    "Week 1": "",
    "Player Name": "",
    "Rush Yards": "",
    "Rush TD": "",
    "Rec Yards": "",
    "Rec TD": "",
    "Pass Yards": "",
    "Pass TD": "",
    "Interceptions": "",
    "Fumbles": "",
    "2PC": "",
    "Win/Lose": "",
    "Week Total": ""
  },
  {
    "Week 1": "Week 3",
    "Player Name": "Player Name",
    "Rush Yards": "Rush Yards",
    "Rush TD": "Rush TD",
    "Rec Yards": "Rec Yards",
    "Rec TD": "Rec TD",
    "Pass Yards": "Pass Yards",
    "Pass TD": "Pass TD",
    "Interceptions": "Interceptions",
    "Fumbles": "Fumbles",
    "2PC": "2PC",
    "Win/Lose": "Win/Lose",
    "Week Total": "Week Total"
  },
  {
    "Week 1": "",
    "Player Name": "Russell Wilson",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "Lamar Jackson",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "Drew Brees",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "NA",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "Patrick Mahomes",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "",
    "Rush Yards": "",
    "Rush TD": "",
    "Rec Yards": "",
    "Rec TD": "",
    "Pass Yards": "",
    "Pass TD": "",
    "Interceptions": "",
    "Fumbles": "",
    "2PC": "",
    "Win/Lose": "",
    "Week Total": ""
  },
  {
    "Week 1": "Week 4",
    "Player Name": "Player Name",
    "Rush Yards": "Rush Yards",
    "Rush TD": "Rush TD",
    "Rec Yards": "Rec Yards",
    "Rec TD": "Rec TD",
    "Pass Yards": "Pass Yards",
    "Pass TD": "Pass TD",
    "Interceptions": "Interceptions",
    "Fumbles": "Fumbles",
    "2PC": "2PC",
    "Win/Lose": "Win/Lose",
    "Week Total": "Week Total"
  },
  {
    "Week 1": "",
    "Player Name": "Russell Wilson",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "Lamar Jackson",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "Drew Brees",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "Patrick Mahomes",
    "Rush Yards": 0,
    "Rush TD": 0,
    "Rec Yards": 0,
    "Rec TD": 0,
    "Pass Yards": 0,
    "Pass TD": 0,
    "Interceptions": 0,
    "Fumbles": 0,
    "2PC": 0,
    "Win/Lose": "",
    "Week Total": 0
  },
  {
    "Week 1": "",
    "Player Name": "",
    "Rush Yards": "",
    "Rush TD": "",
    "Rec Yards": "",
    "Rec TD": "",
    "Pass Yards": "",
    "Pass TD": "",
    "Interceptions": "",
    "Fumbles": "",
    "2PC": "",
    "Win/Lose": "",
    "Week Total": ""
  }
];
